### ISSUE TITLE
Add support for mpsz notation

### ISSUE THREAD

**Issue by gondolyr** [DrCheeseFace/mahc#4]
The [mpsz notation](https://mirrors.rit.edu/CTAN/graphics/mahjong/mahjong.pdf) is a widely accepted serialized format to represent mahjong tiles. Having this supported would make it more convenient for some users.

| Suit Shorthand | Suit |
|:----------------------:|:------:|
| m                         | Manzu |
| p                           | Pinzu  |
| s                            | Souzu |
| z                            | Honor |

|   | 0                               | 1                           | 2                           | 3                           | 4                           | 5                           | 6                           | 7                                       | 8                           | 9                           |
|:-:|:-------------------------------:|:---------------------------:|:---------------------------:|:---------------------------:|:---------------------------:|:---------------------------:|:---------------------------:|:---------------------------------------:|:---------------------------:|:---------------------------:|
| m | <span class="tile red">🀋</span> | <span class="tile">🀇</span> | <span class="tile">🀈</span> | <span class="tile">🀉</span> | <span class="tile">🀊</span> | <span class="tile">🀋</span> | <span class="tile">🀌</span> | <span class="tile">🀍</span>             | <span class="tile">🀎</span> | <span class="tile">🀏</span> |
| p | <span class="tile red">🀝</span> | <span class="tile">🀙</span> | <span class="tile">🀚</span> | <span class="tile">🀛</span> | <span class="tile">🀜</span> | <span class="tile">🀝</span> | <span class="tile">🀞</span> | <span class="tile">🀟</span>             | <span class="tile">🀠</span> | <span class="tile">🀡</span> |
| s | <span class="tile red">🀔</span> | <span class="tile">🀐</span> | <span class="tile">🀑</span> | <span class="tile">🀒</span> | <span class="tile">🀓</span> | <span class="tile">🀔</span> | <span class="tile">🀕</span> | <span class="tile">🀖</span>             | <span class="tile">🀗</span> | <span class="tile">🀘</span> |
| z | <span class="tile">🀫</span>     | <span class="tile">🀀</span> | <span class="tile">🀁</span> | <span class="tile">🀂</span> | <span class="tile">🀃</span> | <span class="tile">🀆</span> | <span class="tile">🀅</span> | <span class="red-dragon-tile">🀄</span> |                             |                             |

`0m`, `0p`, and `0s` are red 5s.

For example,

`3s4s5s` would be

# 🀒🀓🀔

or 3-4-5 souzu (bamboo).

A more complex example:

`2489m 3446p 14s 226z`

which would be

# 🀈🀊🀎🀏🀛🀜🀜🀞🀐🀓🀁🀁🀅

**Comment by DrCheeseFace** [comment]
yes this is a good idea,
- handling aka doras might ambiguate the --dora flag since it handles dora and uradora but not akadora if we add its representation.
should we exclude counting this dora and only use the dora flags number?

**Comment by gondolyr** [comment]
I'm thinking that the `--dora` option could be repurposed for users to note which tiles are dora tiles. I was thinking people could use the dora indicator tiles but why not just provide the dora tiles themselves `¯\_(ツ)_/¯`. If this path is chosen, the parser would need to account for duplicate dora tiles so passing `33p` would mean that `3p` are each worth 2 extra han.

**Comment by DrCheeseFace** [comment]
ooo i dont think itll make sense to use mpsz notation and exclude some of it just to keep the ```--dora``` working as it is
changing the flag to accept tiles instead is probably the way forward

**Comment by DrCheeseFace** [comment]
its best we do the change to the dora flag first before adding support for mpsz notation

**Comment by gondolyr** [comment]
If you do add red 5 support, depending on your implementation, you may need to implement the [`PartialEq` trait](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html#how-can-i-implement-partialeq) manually. I've done this for my mahjong library and while it wasn't too difficult, I have to have additional logic to check if it is specifically a red five through a method called `is_red_five()` and `is_regular_five()` for convenience. Your mileage may vary.

**Comment by DrCheeseFace** [comment]
i could do a check for ```0``` at the start of ```Hand::new()``` and replace it with ```5``` and store the suits i got akadoras for in the hand struct.
lil clunky but its just a calculator so it wont have much other uses for actually handling akadoras.

as for funky unicode, ahhh why not

**Comment by DrCheeseFace** [comment]
actually never mind i think there are rulesets that have multiple akadoras in a suit, so just some count of doras, which includes aka ura and normal doras prolly.
so ```Hand::new()``` would also get passed the dora tiles now.

**Comment by DrCheeseFace** [comment]
```rust        
let value = win.chars().nth(0).unwrap().to_string();
let suitchar = &win.chars().nth(1).unwrap().to_string();
let suit = Suit::suit_from_string(&suitchar, &value)?;
let value = if suitchar == "z" {
    match value.as_str() {
        "1" => "E".to_string(),
        "2" => "S".to_string(),
        "3" => "W".to_string(),
        "4" => "N".to_string(),
        "5" => "w".to_string(),
        "6" => "g".to_string(),
        "7" => "r".to_string(),
        _ => value,
    }
} else {
    value
};
````
currently ive just implemented  mpsz for honor tiles (not akadoras).in a somewhat messy way
this method is used multiple times in ```hand.rs``` and ```tile_group.rs``` 
we could make a method that takes a tiles string eg: ```7z``` and returns the suit and value -> ```Suit::Dragon``` and ```r``` but where would it go.
wed have to turn values into enums or something like that but this would change quite a bit. possibly a value struct needed.
any ideas? 
@gondolyr

**Comment by gondolyr** [comment]
I was thinking the [`TryFrom`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) trait could be implemented for the `TileGroup` struct. Extending the functionality of `TileGroup` seems to make the most sense to have the minimum amount of changes.

Since there are a limited amount of tiles, changing the tile type to an enum makes sense to, though I can't say with certainty that this is a better approach for your app. All in all, I don't have a particular preference for this right now; I do think that centralizing the parsing into a struct or enum implementation would be best to start with.

---

Parsing mpsz notation is not something I've worked on a lot and there are different styles to its format.

One is where each tile is individually defined:

```
1p1p9p 1s9s 1m9m 1z2z3z4z5z6z7z
```

However, from what I've seen online, this style is more common where it groups tiles of the same suit together:

```
119p 19s 19m 1234567z
```

![](https://github.com/Schmytzi/mahjong-tex/raw/main/doc/13orphans.png)

There's also the meld syntax (`'` and `"`) to show chii, pon, and kan calls like so:

```
X44Xp-123's-50"5m-33?z
```

![](https://github.com/Schmytzi/mahjong-tex/raw/main/doc/expansions.png)

Writing a complete parser can be its own project, though for an MVP, you could support the easiest path where it looks like this:

```
1p1p9p 1s9s 1m9m 1z2z3z4z5z6z7z
```

**Comment by DrCheeseFace** [comment]
@gondolyr is this along the lines of what you expected?
dw most of the lines added were test cases or corrections to test cases

**Comment by gondolyr** [comment]
I haven't taken the time to fully review the PR, though I do have reservations about the struct having the `isaka` field when most `TileGroup`s won't need to use that field.

I'm biased toward using an enum to represent all tiles, though the `TileGroup` struct could stay while the `value`, `suit`, and `isaka` fields get replaced with the `Tile` enum. I'm still thinking about what would be best.

Something like this is along the lines of what I'm thinking:

```rust
// The enum variant names don't need to use the Romaji but this is just an example.
#[derive(Debug)]
enum Tile {
    /// 1 of characters.
    IiMan,
    /// 2 of characters.
    RyanMan,
    /// Red 5 of characters.
    AkaUuMan,
    /// 5 of characters.
    UuMan,
    /// 1 of circles.
    IiPin,
    /// 2 of circles.
    RyanPin,
    /// Red 5 of circles.
    AkaUuPin,
    /// 5 of circles.
    UuPin,
    /// 1 of bamboo.
    IiSou,
    /// 2 of bamboo.
    RyanSou,
    /// Red 5 of bamboo.
    AkaUuSou,
    /// 5 of bamboo.
    UuSou
    /// East wind.
    Ton,
    /// White dragon.
    Haku,
}

impl PartialEq for Tile {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::UuMan, Self::AkaUuMan)
            | (Self::AkaUuMan, Self::UuMan)
            | (Self::UuPin, Self::AkaUuPin)
            | (Self::AkaUuPin, Self::UuPin)
            | (Self::UuSou, Self::AkaUuSou)
            | (Self::AkaUuSou, Self::UuSou) => true,
            (this, other_tile) => this == *other_tile
    }
}

struct TileGroup {
    tile: Tile,
    isopen: bool,
    group_type: GroupType,
    isterminal: bool,
}

#[cfg(test)]
mod tests {
    use super::Tile;

    #[test]
    fn red_5_man_equal_to_5_man() {
        assert_eq!(Tile::AkaUuMan, Tile::UuMan);
        assert_eq!(Tile::UuMan, Tile::AkaUuMan);
    }
}
```

**Comment by DrCheeseFace** [comment]
how would you represent a tile group like 406m with this method

**Comment by gondolyr** [comment]
Instead of having a raw string, which contains arbitrary values, the values need to be converted (parsed) into the appropriate `Tile` variant.  The `Suit::suit_from_string()` method would be helpful here.

Something like this (probably needs refinement):

```rust
use std::str::FromStr;

impl FromStr for Tile {
    type Err = HandErr;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let tile = match Suit::suit_from_string(s)? {
            Suit::Manzu => {
                match s {
                    "1" => Tile::IiMan,
                    "2" => Tile::RyanMan,
                    "0" => Tile::AkaUuMan,
                    "5" => Tile::UuMan,
                    _ => return Err(Self::Err),
                }
            }
            Suit::Pinzu => {
                match s {
                    "1" => Tile::IiPin,
                    // remaining tiles
                }
            }
            Suit::Wind => {
                match s {
                    "1" => Tile::East,
                    // remaining tiles
                }
            }
            // remaining suits
        };

        Ok(tile)
    }
}
```

**Comment by DrCheeseFace** [comment]
Tile group only holds the value of the first tile in a group eg: 123m -> value is 1 or Iiman
however if you have something like 406m -> the value is 4 and the akadora is information lost about the tile group.
tilegroup would have to store a vec of tiles. 
```rust
struct TileGroup {
    tile: Vec<Tile>,
    isopen: bool,
    group_type: GroupType,
    isterminal: bool,
}
```

**Comment by gondolyr** [comment]
Then I misunderstood how `TileGroup` originally stores the tile value and it seems you have a path forward.
